- op: replace
  path: /spec/source/repoURL
  value: 'https://gitlab.consulting.redhat.com/intelligent-application-practice/xray/cluster-bootstrap.git'
- op: replace
  path: /spec/source/targetRevision
  value: main
